name: Train Models

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install wandb imbalanced-learn scikit-learn pandas joblib

    - name: Train RandomForest
      run: |
        python scripts/model_rf.py

    - name: Train AdaBoost
      run: |
        python scripts/model_ada.py

    - name: Upload W&B API key
      env:
        WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
      run: echo "W&B API key is set"
